version: '3.8'
services:
  backend:
    build:
      context: .
    command: uvicorn api:app --host 0.0.0.0 --port 5001
    ports:
      - "5001:5001"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./eftopia-hack-tool:/app
    command: ["sh", "-c", "npm install && ng serve --host 0.0.0.0 --port 4200"]
    ports:
      - "4200:4200"
